#!/usr/bin/env node
// SoundCloud 프로필의 곡 목록을 tracks.ts로 생성한다.
//
// 공식 API(api.soundcloud.com)는 client_id가 필요하고 발급이 막혀 있어, 프로필 페이지의
// JS 번들에서 익명 client_id를 뽑아 api-v2를 호출한다. 비공식 경로라 언제든 깨질 수 있으므로
// **실패해도 종료 코드 0으로 끝낸다** — 커밋된 tracks.ts로 빌드가 계속 진행돼야 한다.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const USER_ID = 51779680;
const PROFILE = 'https://soundcloud.com/danwooking/tracks';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/131.0 Safari/537.36';
const TIMEOUT_MS = 20_000;

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'entities',
  'track',
  'model',
  'constants',
  'tracks.ts',
);

const warn = (message) => console.warn(`[sync-tracks] ${message}`);

// 생성물이 Prettier(singleQuote)와 어긋나면 커밋마다 포맷 diff가 난다
const q = (value) =>
  `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;

async function get(url) {
  const res = await fetch(url, { headers: { 'user-agent': UA }, signal: AbortSignal.timeout(TIMEOUT_MS) });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res;
}

async function findClientId() {
  const html = await (await get(PROFILE)).text();
  const bundles = [...html.matchAll(/<script[^>]+src="(https:\/\/a-v2\.sndcdn\.com[^"]+)"/g)].map((m) => m[1]);
  // client_id는 보통 마지막에 로드되는 번들에 있다
  for (const src of bundles.reverse()) {
    const hit = (await (await get(src)).text()).match(/client_id[=:"]{1,3}([a-zA-Z0-9]{32})/);
    if (hit) return hit[1];
  }
  throw new Error('번들에서 client_id를 찾지 못했습니다');
}

// artwork_url은 …-large.jpg 또는 …-large.png로 온다. 확장자를 고정하면 절반 이상이 404다.
function splitArtwork(url) {
  const parts = url.match(/^(.*)-[a-z0-9]+(\.jpg|\.png)$/);
  if (!parts) throw new Error(`아트워크 URL 형식을 알 수 없습니다: ${url}`);
  return { base: parts[1], ext: parts[2] };
}

// SoundCloud가 주는 한글 제목은 상당수가 NFD(자모 분해형)다. 브라우저는 알아서 합쳐 그리지만
// Satori(OG 카드)는 합치지 않아 '바다'가 'ㅂㅏㄷㅏ'로 나온다. 들어올 때 한 번 NFC로 고정한다.
const nfc = (value) => String(value).normalize('NFC');

function toTrack(raw) {
  const { base, ext } = splitArtwork(raw.artwork_url);
  return {
    id: raw.id,
    title: nfc(raw.title),
    permalinkUrl: raw.permalink_url,
    artworkBase: base,
    artworkExt: ext,
    waveformUrl: raw.waveform_url,
    durationMs: raw.duration,
    genre: nfc(raw.genre || 'Unclassified'),
  };
}

function render(tracks) {
  const body = tracks
    .map(
      (t) => `  {
    id: ${t.id},
    title: ${q(t.title)},
    permalinkUrl: ${q(t.permalinkUrl)},
    artworkBase: ${q(t.artworkBase)},
    artworkExt: ${q(t.artworkExt)},
    waveformUrl: ${q(t.waveformUrl)},
    durationMs: ${t.durationMs},
    genre: ${q(t.genre)},
  },`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/sync-tracks.mjs — 직접 수정하지 말 것.
// 갱신: pnpm --filter soundlab sync-tracks
import type { Track } from '../types';

export const TRACKS: readonly Track[] = [
${body}
] as const;
`;
}

try {
  const clientId = await findClientId();
  const url = `https://api-v2.soundcloud.com/users/${USER_ID}/tracks?client_id=${clientId}&limit=50`;
  const { collection } = await (await get(url)).json();

  if (!Array.isArray(collection) || collection.length === 0) {
    throw new Error('빈 목록을 받았습니다 (성공이 아니라 실패로 취급)');
  }

  const tracks = collection.map(toTrack);
  writeFileSync(OUT, render(tracks), 'utf8');
  console.log(`[sync-tracks] ${tracks.length}곡 생성 → ${OUT.replace(process.cwd(), '.')}`);
} catch (error) {
  warn(`갱신 실패: ${error.message}`);
  try {
    if (existsSync(OUT)) {
      const count = (readFileSync(OUT, 'utf8').match(/^\s{4}id: /gm) ?? []).length;
      warn(`기존 tracks.ts를 그대로 사용합니다 (${count}곡). 빌드는 계속됩니다.`);
    } else {
      warn('tracks.ts가 없어 빈 목록으로 생성합니다. 손으로 채워야 합니다.');
      mkdirSync(dirname(OUT), { recursive: true });
      writeFileSync(OUT, render([]), 'utf8');
    }
  } catch (fallbackError) {
    // 폴백까지 실패해도 빌드를 막지 않는다
    warn(`폴백 처리도 실패했습니다: ${fallbackError.message}`);
  }
  process.exitCode = 0;
}
