#!/usr/bin/env node
// SoundCloud 프로필의 곡 목록을 tracks.ts로 생성한다.
//
// 공식 API(api.soundcloud.com)는 client_id가 필요하고 발급이 막혀 있어, 프로필 페이지의
// JS 번들에서 익명 client_id를 뽑아 api-v2를 호출한다. 비공식 경로라 언제든 깨질 수 있으므로
// **실패해도 종료 코드 0으로 끝낸다** — 커밋된 tracks.ts로 빌드가 계속 진행돼야 한다.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const USER_ID = 51779680;
const PROFILE = 'https://soundcloud.com/danwooking/tracks';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/131.0 Safari/537.36';
const TIMEOUT_MS = 20_000;

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'entities',
  'track',
  'model',
  'constants',
  'tracks.ts',
);

// ImageResponse가 process.cwd() 기준으로 읽는다. 앱 루트의 assets/ 에 둔다.
const FONT_OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'og-title.ttf');

const warn = (message) => console.warn(`[sync-tracks] ${message}`);

// 생성물이 Prettier(singleQuote)와 어긋나면 커밋마다 포맷 diff가 난다
const q = (value) =>
  `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;

async function get(url, userAgent = UA) {
  const res = await fetch(url, { headers: { 'user-agent': userAgent }, signal: AbortSignal.timeout(TIMEOUT_MS) });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res;
}

async function findClientId() {
  const html = await (await get(PROFILE)).text();
  const bundles = [...html.matchAll(/<script[^>]+src="(https:\/\/a-v2\.sndcdn\.com[^"]+)"/g)].map((m) => m[1]);
  // client_id는 보통 마지막에 로드되는 번들에 있다
  for (const src of bundles.reverse()) {
    const hit = (await (await get(src)).text()).match(/client_id[=:"]{1,3}([a-zA-Z0-9]{32})/);
    if (hit) return hit[1];
  }
  throw new Error('번들에서 client_id를 찾지 못했습니다');
}

// artwork_url은 …-large.jpg 또는 …-large.png로 온다. 확장자를 고정하면 절반 이상이 404다.
function splitArtwork(url) {
  const parts = url.match(/^(.*)-[a-z0-9]+(\.jpg|\.png)$/);
  if (!parts) throw new Error(`아트워크 URL 형식을 알 수 없습니다: ${url}`);
  return { base: parts[1], ext: parts[2] };
}

// SoundCloud가 주는 한글 제목은 상당수가 NFD(자모 분해형)다. 브라우저는 알아서 합쳐 그리지만
// Satori(OG 카드)는 합치지 않아 '바다'가 'ㅂㅏㄷㅏ'로 나온다. 들어올 때 한 번 NFC로 고정한다.
const nfc = (value) => String(value).normalize('NFC');

function toTrack(raw) {
  const { base, ext } = splitArtwork(raw.artwork_url);
  return {
    id: raw.id,
    title: nfc(raw.title),
    permalinkUrl: raw.permalink_url,
    artworkBase: base,
    artworkExt: ext,
    waveformUrl: raw.waveform_url,
    durationMs: raw.duration,
    genre: nfc(raw.genre || 'Unclassified'),
  };
}

function render(tracks) {
  const body = tracks
    .map(
      (t) => `  {
    id: ${t.id},
    title: ${q(t.title)},
    permalinkUrl: ${q(t.permalinkUrl)},
    artworkBase: ${q(t.artworkBase)},
    artworkExt: ${q(t.artworkExt)},
    waveformUrl: ${q(t.waveformUrl)},
    durationMs: ${t.durationMs},
    genre: ${q(t.genre)},
  },`,
    )
    .join('\n');

  return `// AUTO-GENERATED by scripts/sync-tracks.mjs — 직접 수정하지 말 것.
// 갱신: pnpm --filter soundlab sync-tracks
import type { Track } from '@entities/track/model/types';

export const TRACKS: readonly Track[] = [
${body}
] as const;
`;
}

/**
 * OG 카드에 곡 제목을 그리려면 폰트를 바이너리로 넣어야 한다(Satori는 시스템 폰트를 안 쓴다).
 * 한글 폰트 원본은 수 MB라 ImageResponse의 500KB 한도를 넘는다. Google Fonts는 `text=`로
 * 요청한 글자만 담은 서브셋을 주고, 제목에 쓰인 글자 전체가 수십 KB로 떨어진다.
 * 제목이 바뀌면 필요한 글자도 바뀌므로 곡 목록과 같은 시점에 다시 만든다.
 */
async function writeOgFont(tracks) {
  // 카드에 실제로 그리는 문자만 모은다 — 제목·장르 + 고정 문구·숫자.
  const used = tracks.map((t) => `${t.title}${t.genre}`).join('');
  const chars = [...new Set(`${used}SOUNDLABDANWOO 0123456789:·`.split(''))].sort().join('');
  const api = `https://fonts.googleapis.com/css2?family=Gothic+A1:wght@700&text=${encodeURIComponent(chars)}`;
  // 구형 UA로 요청해야 woff2 대신 ttf를 준다. ImageResponse는 woff2를 못 읽는다.
  const css = await (await get(api, 'Mozilla/4.0')).text();
  const found = css.match(/src:\s*url\(([^)]+)\)\s*format\('truetype'\)/);
  if (!found) throw new Error('구글 폰트 응답에서 ttf URL을 찾지 못했습니다');

  const font = Buffer.from(await (await get(found[1])).arrayBuffer());
  mkdirSync(dirname(FONT_OUT), { recursive: true });
  writeFileSync(FONT_OUT, font);
  console.log(`[sync-tracks] OG 폰트 서브셋 ${(font.length / 1024).toFixed(1)}KB (${chars.length}자) → ${FONT_OUT.replace(process.cwd(), '.')}`);
}

try {
  const clientId = await findClientId();
  const url = `https://api-v2.soundcloud.com/users/${USER_ID}/tracks?client_id=${clientId}&limit=50`;
  const { collection } = await (await get(url)).json();

  if (!Array.isArray(collection) || collection.length === 0) {
    throw new Error('빈 목록을 받았습니다 (성공이 아니라 실패로 취급)');
  }

  const tracks = collection.map(toTrack);
  writeFileSync(OUT, render(tracks), 'utf8');
  console.log(`[sync-tracks] ${tracks.length}곡 생성 → ${OUT.replace(process.cwd(), '.')}`);

  // 폰트만 실패해도 곡 목록 갱신은 살린다. 커밋된 서브셋에 없는 글자만 두부로 나온다.
  try {
    await writeOgFont(tracks);
  } catch (fontError) {
    warn(`OG 폰트 갱신 실패: ${fontError.message}. 기존 서브셋을 그대로 사용합니다.`);
  }
} catch (error) {
  warn(`갱신 실패: ${error.message}`);
  try {
    if (existsSync(OUT)) {
      const count = (readFileSync(OUT, 'utf8').match(/^\s{4}id: /gm) ?? []).length;
      warn(`기존 tracks.ts를 그대로 사용합니다 (${count}곡). 빌드는 계속됩니다.`);
    } else {
      warn('tracks.ts가 없어 빈 목록으로 생성합니다. 손으로 채워야 합니다.');
      mkdirSync(dirname(OUT), { recursive: true });
      writeFileSync(OUT, render([]), 'utf8');
    }
  } catch (fallbackError) {
    // 폴백까지 실패해도 빌드를 막지 않는다
    warn(`폴백 처리도 실패했습니다: ${fallbackError.message}`);
  }
  process.exitCode = 0;
}
