import type { QuizQuestion } from '../../types';

// 아코 (노아) 💜 알파카
export const AKO_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'ako-jjigae',
    characterId: 'ako',
    question: '아코의 별미 음식은?',
    options: [
      '아이스 된장찌개',
      '차가운 김치찌개',
      '미지근한 미역국',
      '시원한 갈비탕',
    ],
    correctIndex: 0,
    fact: '진심으로 아이스 된장찌개를 좋아한다고 했어요 🥶',
  },
  {
    id: 'ako-ddeokbokki',
    characterId: 'ako',
    question: '아코가 떡볶이에서 안 먹는 것은?',
    options: ['떡과 어묵', '튀김', '라면 사리', '다 잘 먹는다'],
    correctIndex: 0,
    fact: '튀김에 떡볶이 소스 찍어 먹는 건 좋아해요 🍢',
  },
  {
    id: 'ako-hobby',
    characterId: 'ako',
    question: '아코의 취미 중 하나가 아닌 것은?',
    options: ['게임', '노래', '웨이트', '영화 보기'],
    correctIndex: 0,
    fact: '맏형은 멤버 중에서 게임에 가장 관심이 없습니다 😅',
  },
  {
    id: 'ako-mbti',
    characterId: 'ako',
    question: '아코의 MBTI는?',
    options: ['ISFJ-A', 'ENFP-T', 'ESTP-A', 'INTP-T'],
    correctIndex: 0,
    fact: '챙기는 형아 캐릭터, 이전엔 ISTJ였다가 ISFJ-A로 🦙',
  },
  {
    id: 'ako-color',
    characterId: 'ako',
    question: '아코의 시그니처 색깔은?',
    options: ['보라색 💜', '파란색 💙', '분홍 💗', '검정 🖤'],
    correctIndex: 0,
    fact: '알파카와 잘 어울리는 보라색이 아코의 색 🦙',
  },
  {
    id: 'ako-animal',
    characterId: 'ako',
    question: '아코를 대표하는 동물은?',
    options: ['알파카', '말티즈', '늑대', '돌고래'],
    correctIndex: 0,
    fact: '폭신폭신 알파카가 아코의 대표 동물 🦙',
  },
  {
    id: 'ako-nickname',
    characterId: 'ako',
    question: '아코의 별명이 아닌 것은?',
    options: ['멍멍이', '공주', '할머니', '스포일러 요정'],
    correctIndex: 0,
    fact: '공주·할머니·스포일러 요정·체육관 쥐가 아코의 별명 👑',
  },
  {
    id: 'ako-protein',
    characterId: 'ako',
    question: '아코가 가장 좋아하는 영양소는?',
    options: ['단백질', '탄수화물', '지방', '비타민'],
    correctIndex: 0,
    fact: '단백질 매니아, "체육관 쥐"라는 별명이 어울려요 💪',
  },
  {
    id: 'ako-pizza',
    characterId: 'ako',
    question: '아코가 하와이안 피자를 먹는 방식은?',
    options: [
      '작은 파인애플만 데코처럼',
      '파인애플 빼고',
      '파인애플 두 배',
      '안 먹음',
    ],
    correctIndex: 0,
    fact: '큰 파인애플은 별로, 작은 조각만 데코로 좋아해요 🍍',
  },
  {
    id: 'ako-dislike',
    characterId: 'ako',
    question: '아코가 즐기지 않는 음식은?',
    options: ['매운·비린 음식, 해산물', '단 음식', '고기', '튀김'],
    correctIndex: 0,
    fact: '매운 음식·해산물 모두 잘 안 먹어요 🐟❌',
  },
  {
    id: 'ako-favorite-song',
    characterId: 'ako',
    question: 'PLCO 곡 중 아코의 최애 자작곡은?',
    options: ['여섯 번째 여름', '기다릴게', 'Virtual Idol', 'Way 4 Luv'],
    correctIndex: 0,
    fact: '아코가 가장 아끼는 자작곡이 "여섯 번째 여름" 🌻',
  },
  {
    id: 'ako-cool',
    characterId: 'ako',
    question: '아코가 본인 성격을 한 단어로 정의한 것은?',
    options: ['Cool', 'Lovely', 'Funny', 'Cute'],
    correctIndex: 0,
    fact: '본인 정의는 단호하게 "Cool" 😎',
  },
  {
    id: 'ako-jump',
    characterId: 'ako',
    question: '아코의 의외의 특기는?',
    options: ['높이뛰기', '암벽등반', '양궁', '수영'],
    correctIndex: 0,
    fact: '작사·작곡 외 의외의 특기가 높이뛰기 🏃',
  },
  {
    id: 'ako-line',
    characterId: 'ako',
    question: '아코가 은코와 함께 만든 라인은?',
    options: ['No-line (노라인)', 'Yes-line', 'Pro-line', 'Dance-line'],
    correctIndex: 0,
    fact: '"수준 높은 개그"를 하는 자만 들어갈 수 있다는 노라인 😆',
  },
  {
    id: 'ako-dance',
    characterId: 'ako',
    question: '댄스 챌린지에서 아코의 약점은?',
    options: [
      '안무 외우는 데 시간이 걸림',
      '리듬을 못 탐',
      '체력 좋음',
      '안무 천재',
    ],
    correctIndex: 0,
    fact: '댄스 라인 두 명과 달리 안무 외우기에 시간이 걸려요 💃',
  },
  {
    id: 'ako-realname',
    characterId: 'ako',
    question: '아코의 본명은?',
    options: ['한노아', '남예준', '도은호', '유하민'],
    correctIndex: 0,
    fact: '한노아, 그래서 영문 별명도 Noah 🦙',
  },
  {
    id: 'ako-bloodtype',
    characterId: 'ako',
    question: '아코의 혈액형은?',
    options: ['O형', 'A형', 'B형', 'AB형'],
    correctIndex: 0,
    fact: 'O형, 물병자리, PLCO 최연장자 🌊',
  },
  {
    id: 'ako-height',
    characterId: 'ako',
    question: '아코의 키는?',
    options: ['179cm', '170cm', '184cm', '185cm'],
    correctIndex: 0,
    fact: '179cm, 멤버 중에서는 중간 정도예요 📏',
  },
  {
    id: 'ako-role',
    characterId: 'ako',
    question: 'PLCO에서 아코의 메인 포지션은?',
    options: ['메인 보컬', '메인 댄서', '메인 래퍼', '리더'],
    correctIndex: 0,
    fact: '깊고 파워풀한 보이스, 록 발라드 잘 부르는 메인 보컬 🎤',
  },
  {
    id: 'ako-genre',
    characterId: 'ako',
    question: '아코가 가장 잘 부르는 장르는?',
    options: ['록 발라드', '트로트', '메탈', '재즈'],
    correctIndex: 0,
    fact: '록 발라드 부를 때 반응이 가장 폭발적이에요 🎸',
  },
  {
    id: 'ako-instrument',
    characterId: 'ako',
    question: '아코가 다룰 수 있는 악기는?',
    options: ['기타', '드럼', '바이올린', '피아노만'],
    correctIndex: 0,
    fact: '예준이만큼은 아니지만 기타도 칩니다 🎸',
  },
  {
    id: 'ako-debut-highnote',
    characterId: 'ako',
    question: '"기다릴게" 후반부 고음 파트는 어떻게 만들어졌나?',
    options: [
      '아코가 녹음실에서 즉흥으로',
      '예준이 작곡',
      '은호가 추가',
      '프로듀서 지시',
    ],
    correctIndex: 0,
    fact: '뭔가 부족하다 싶어서 녹음 도중에 즉흥적으로 떠올렸어요 ✨',
  },
  {
    id: 'ako-pllistmas',
    characterId: 'ako',
    question: '"Merry PLLIstmas" 멜로디를 어떻게 보존했나?',
    options: [
      '한 시간 동안 흥얼거리며 집으로',
      '바로 악보로',
      '동료에게 전화로 불러줌',
      '잊어버렸다가 다시 떠올림',
    ],
    correctIndex: 0,
    fact: '눈 보다가 떠올린 멜로디, 폰이 추위에 꺼지자 한 시간 흥얼흥얼 🎄',
  },
  {
    id: 'ako-perfectionist',
    characterId: 'ako',
    question: '아코의 성격을 잘 표현하는 단어는?',
    options: ['완벽주의자', '느긋함', '즉흥적', '게으름'],
    correctIndex: 0,
    fact: '완벽주의자, 운동도 음악도 진심 💪',
  },
  {
    id: 'ako-wink',
    characterId: 'ako',
    question: '아코가 윙크할 때 일어나는 일은?',
    options: ['눈에서 하트가 나옴', '반짝임', '꽃이 핌', '아무 일 없음'],
    correctIndex: 0,
    fact: '윙크 시 눈에서 하트가 튀어나오는 특수 능력 💜',
  },
  {
    id: 'ako-laugh',
    characterId: 'ako',
    question: '아코가 웃을 때 일어나는 일은?',
    options: ['얼굴이 반짝임', '바람이 분다', '꽃잎이 떨어진다', '특별한 일 없음'],
    correctIndex: 0,
    fact: '웃을 때 얼굴에서 반짝임이 나타나는 능력 ✨',
  },
  {
    id: 'ako-bringing',
    characterId: 'ako',
    question: '아코를 PLCO에 데려온 멤버는?',
    options: ['예코이', '밤코', '은코', '하코이'],
    correctIndex: 0,
    fact: '예코이가 첫 트레이니로서 아코·은코를 모았어요 🤝',
  },
  {
    id: 'ako-dislike-cause',
    characterId: 'ako',
    question: '아코가 가장 견디지 못하는 환경은?',
    options: ['시끄러운 곳·끈적한 것', '추운 곳', '비 오는 날', '낯선 사람 많은 곳'],
    correctIndex: 0,
    fact: '소음·끈적함 둘 다 싫어해요 🙅',
  },
  {
    id: 'ako-eat-before',
    characterId: 'ako',
    question: '아코가 녹음 직전에 든든히 챙겨먹는 것은?',
    options: ['라면이나 피자', '주먹밥', '에너지바', '안 먹음'],
    correctIndex: 0,
    fact: '녹음 전엔 든든하게 먹어야 한대요 🍕',
  },
];
