import type { QuizQuestion } from '../../types';

// 밤코 (밤비) 💗 사슴
export const BAMKO_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'bamko-noodle',
    characterId: 'bamko',
    question: '밤코가 즐겨 먹는 면 요리는?',
    options: ['평양냉면', '비빔국수', '잔치국수', '우동'],
    correctIndex: 0,
    fact: '담백한 평양냉면 매니아입니다 🥶',
  },
  {
    id: 'bamko-game',
    characterId: 'bamko',
    question: '밤코가 좋아하는 게임 스타일은?',
    options: [
      '카트라이더 / 크레이지 아케이드 (캐주얼)',
      'FPS / 슈팅',
      'RPG',
      '격투게임',
    ],
    correctIndex: 0,
    fact: '단순하고 전략 부담 없는 캐주얼 게임을 좋아해요 🏎️',
  },
  {
    id: 'bamko-pet',
    characterId: 'bamko',
    question: '밤코가 좋아하는 것은?',
    options: ['강아지와 산책', '고양이 카페', '햄스터 키우기', '동물 관심 없음'],
    correctIndex: 0,
    fact: '강아지 진심이고 산책도 좋아합니다 🐶',
  },
  {
    id: 'bamko-mbti',
    characterId: 'bamko',
    question: '밤코의 MBTI는?',
    options: ['INTJ-A', 'INFP-T', 'ENFJ-A', 'ESTP-T'],
    correctIndex: 0,
    fact: '이전엔 INFP-T였다가 지금은 INTJ-A 🧠',
  },
  {
    id: 'bamko-color',
    characterId: 'bamko',
    question: '밤코의 시그니처 색은?',
    options: ['분홍 💗', '파란색 💙', '빨강 ❤️', '보라색 💜'],
    correctIndex: 0,
    fact: '핑크 머리, 핑크 하트가 밤코의 상징 🩷',
  },
  {
    id: 'bamko-animal',
    characterId: 'bamko',
    question: '밤코를 대표하는 동물은?',
    options: ['사슴', '말티즈', '여우', '햄스터'],
    correctIndex: 0,
    fact: '대표 동물은 사슴, 별명에 말티즈도 있어요 🦌',
  },
  {
    id: 'bamko-nickname',
    characterId: 'bamko',
    question: '밤코의 대표 별명은?',
    options: ['핑크쪼꼬미 (핑쬬)', '검정고양이', '늑댕이', '돌고래'],
    correctIndex: 0,
    fact: '핑크 머리 + 작은 키 콤보로 핑쬬가 됐어요 🩷',
  },
  {
    id: 'bamko-height',
    characterId: 'bamko',
    question: '멤버 중 밤코의 키 순위는?',
    options: ['가장 작음 (174cm)', '가장 큼', '중간', '두번째로 큼'],
    correctIndex: 0,
    fact: '174cm로 멤버 중 가장 작아 "쪼꼬미"라는 별명이 붙었어요 📏',
  },
  {
    id: 'bamko-fear',
    characterId: 'bamko',
    question: '밤코가 무서워하는 동물은?',
    options: ['비둘기·앵무새', '강아지', '고양이', '햄스터'],
    correctIndex: 0,
    fact: '의외로 새 종류, 특히 비둘기와 앵무새를 무서워해요 🐦',
  },
  {
    id: 'bamko-crab',
    characterId: 'bamko',
    question: '밤코가 한 자리에서 많이 먹는 음식은?',
    options: ['간장게장 (20개 먹다 배탈)', '닭발', '회 (10접시)', '피자 한판'],
    correctIndex: 0,
    fact: '무한리필집에서 20개 먹다 탈 났을 정도로 좋아해요 🦀',
  },
  {
    id: 'bamko-sushi',
    characterId: 'bamko',
    question: '밤코가 음식 이상형 월드컵에서 꼽은 음식은?',
    options: ['회', '치킨', '떡볶이', '햄버거'],
    correctIndex: 0,
    fact: '회를 매우 좋아한다고 했고, 같은 이유로 초밥도 좋아해요 🍣',
  },
  {
    id: 'bamko-realname',
    characterId: 'bamko',
    question: '밤코의 본명은?',
    options: ['채봉구', '남예준', '도은호', '한노아'],
    correctIndex: 0,
    fact: '"채봉구귀엽다"의 줄임말이 별명 "채봉비"에요 🤍',
  },
  {
    id: 'bamko-partner',
    characterId: 'bamko',
    question: '밤코와 함께 안무를 짜는 멤버는?',
    options: ['하코이', '예코이', '아코', '은코'],
    correctIndex: 0,
    fact: '댄스 라인 콤비, PLCO 안무 거의 다 둘이 만들어요 💃',
  },
  {
    id: 'bamko-gym',
    characterId: 'bamko',
    question: '밤코가 데뷔 후 시작한 운동은?',
    options: ['헬스 (꾸준히)', '러닝', '수영', '복싱'],
    correctIndex: 0,
    fact: '데뷔 이후 어느 순간부터 시작해서 지금도 꾸준히 해요 💪',
  },
  {
    id: 'bamko-sibling',
    characterId: 'bamko',
    question: '밤코의 가족 구성은?',
    options: ['여동생이 있음', '외동', '쌍둥이 형', '남동생'],
    correctIndex: 0,
    fact: '여동생이 있는 오빠 포지션이에요 👨‍👧',
  },
  {
    id: 'bamko-bloodtype',
    characterId: 'bamko',
    question: '밤코의 혈액형은?',
    options: ['B형', 'A형', 'O형', 'AB형'],
    correctIndex: 0,
    fact: 'B형, 게자리, 174cm 핑크 머리 🦌',
  },
  {
    id: 'bamko-spicy',
    characterId: 'bamko',
    question: '밤코가 자랑하는 미각은?',
    options: ['맵부심 (불닭볶음면)', '단맛', '신맛', '쓴맛'],
    correctIndex: 0,
    fact: '맵부심 있지만 은코는 거짓이라고 주장해요 🔥',
  },
  {
    id: 'bamko-alcohol',
    characterId: 'bamko',
    question: '밤코의 술 취향은?',
    options: [
      '잘 못 마시고 맥주 선호',
      '소주 매니아',
      '하이볼 매니아',
      '술 안 마심',
    ],
    correctIndex: 0,
    fact: '잘 못 마시는 편, 마실 때는 맥주를 선호해요 🍺',
  },
  {
    id: 'bamko-bug',
    characterId: 'bamko',
    question: '밤코가 벌레를 만나면?',
    options: [
      '아무렇지도 않게 잡거나 굴림',
      '도망감',
      '소리 지르며 무서워함',
      '못 본 척',
    ],
    correctIndex: 0,
    fact: '콩벌레를 굴리고 바퀴벌레도 망설임 없이 잡아요 🪲',
  },
  {
    id: 'bamko-pickup',
    characterId: 'bamko',
    question: '밤코의 강점인 게임 타입은?',
    options: ['단순 피지컬 게임 (황새·피카츄배구)', '전략 시뮬레이션', 'RPG', '리듬 게임'],
    correctIndex: 0,
    fact: '피지컬 베이스 게임은 다 잘해요 🏆',
  },
  {
    id: 'bamko-nickname-real',
    characterId: 'bamko',
    question: '밤코의 본명 "채봉구"에서 파생된 별명은?',
    options: ['채봉비 (채봉구귀엽다)', '채구비', '채채비', '봉봉이'],
    correctIndex: 0,
    fact: '"채봉구귀엽다" 줄임말이 별명 "채봉비"에요 🤍',
  },
  {
    id: 'bamko-noodle-eat',
    characterId: 'bamko',
    question: '밤코가 평양냉면 먹는 방식은?',
    options: [
      '면 추가, 국물까지, 고춧가루+후추',
      '담백하게 그대로',
      '얼음 많이',
      '비벼서',
    ],
    correctIndex: 0,
    fact: '진짜 매니아는 면 추가에 양념까지 진심 🥶',
  },
  {
    id: 'bamko-rival',
    characterId: 'bamko',
    question: '밤코가 가장 자주 티격태격하는 멤버는?',
    options: ['은코', '예코이', '아코', '하코이'],
    correctIndex: 0,
    fact: '은코가 밤코를 PLCO에 영입해서 더 친한 만큼 자주 다퉈요 ⚡',
  },
  {
    id: 'bamko-crazyarcade',
    characterId: 'bamko',
    question: '크레이지 아케이드에서 밤코의 위치는?',
    options: ['예코이를 이긴 적 있는 고수', '입문자', '못 함', '관심 없음'],
    correctIndex: 0,
    fact: '예코이가 크아 진심인데, 밤코가 한 판 이긴 적이 있어요 🏎️',
  },
  {
    id: 'bamko-color-hair',
    characterId: 'bamko',
    question: '밤코의 상징인 머리 색깔은?',
    options: ['핑크', '파랑', '검정', '갈색'],
    correctIndex: 0,
    fact: '핑크 머리가 핑쬬 별명의 시작 🩷',
  },
  {
    id: 'bamko-shabu',
    characterId: 'bamko',
    question: '밤비가 평양냉면 외에 정말 좋아하는 음식은?',
    options: ['간장게장', '치킨', '곱창', '파스타'],
    correctIndex: 0,
    fact: '간장게장 매니아, 20개까지 먹다 배탈도 났어요 🦀',
  },
  {
    id: 'bamko-dance-position',
    characterId: 'bamko',
    question: 'PLCO에서 밤코의 메인 포지션은?',
    options: ['메인 댄서 & 안무가', '메인 보컬', '메인 래퍼', '리드 보컬'],
    correctIndex: 0,
    fact: '하코이와 함께 PLCO 안무 거의 다 만들어요 💃',
  },
  {
    id: 'bamko-high-voice',
    characterId: 'bamko',
    question: '밤코가 노래에서 담당하는 음역대는?',
    options: ['높은 음역대', '중저음', '베이스', '랩만'],
    correctIndex: 0,
    fact: '댄서이면서도 고음 파트를 자주 맡아요 🎶',
  },
  {
    id: 'bamko-vienna',
    characterId: 'bamko',
    question: '밤코가 좋아하는 카페 메뉴는?',
    options: ['아인슈페너', '바닐라 라떼', '카페모카', '녹차'],
    correctIndex: 0,
    fact: '진한 커피 위 생크림 조합 아인슈페너를 좋아해요 ☕',
  },
];
