import type { QuizQuestion } from '../../types';

// 은코 (은호) ❤️ 늑대
export const EUNKO_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'eunko-ramen',
    characterId: 'eunko',
    question: '은코의 라면 취향은?',
    options: ['진라면 매운맛', '신라면', '안성탕면', '너구리'],
    correctIndex: 0,
    fact: '무조건 진라면 매운맛파입니다 🌶️',
  },
  {
    id: 'eunko-kalguksu',
    characterId: 'eunko',
    question: '은코가 가장 좋아하는 음식으로 매번 꼽는 것은?',
    options: ['바지락 칼국수', '김치 칼국수', '들깨 칼국수', '해물 칼국수'],
    correctIndex: 0,
    fact: '바지락 칼국수를 정말 자주 언급해요 🍜',
  },
  {
    id: 'eunko-game',
    characterId: 'eunko',
    question: '은코의 게임 별명은?',
    options: ['PLCO 대표 겜돌이', '게임 입문자', '게임 안 함', '게임 트롤'],
    correctIndex: 0,
    fact: '공포게임에서도 침착하게 "에임 좋았죠?" 할 정도의 실력파 🎮',
  },
  {
    id: 'eunko-mbti',
    characterId: 'eunko',
    question: '은코의 MBTI는?',
    options: ['ENTP-A', 'ISTJ-T', 'INFP-A', 'ISFJ-T'],
    correctIndex: 0,
    fact: '멤버 중 유일하게 E(외향)를 가진 ENTP-A 🐺',
  },
  {
    id: 'eunko-color',
    characterId: 'eunko',
    question: '은코의 시그니처 색은?',
    options: ['빨강 ❤️', '검정 🖤', '파랑 💙', '분홍 💗'],
    correctIndex: 0,
    fact: '늑대 + 빨강이 은코의 시그니처 🐺❤️',
  },
  {
    id: 'eunko-animal',
    characterId: 'eunko',
    question: '은코의 대표 동물은?',
    options: ['늑대', '여우', '강아지', '늑댕이'],
    correctIndex: 0,
    fact: '일본 무대에서도 본인이 "おおかみ(늑대)"라고 소개해요 🐺',
  },
  {
    id: 'eunko-coffee',
    characterId: 'eunko',
    question: '은코가 가장 좋아하는 음료는?',
    options: ['아이스 아메리카노', '라떼', '카페모카', '핫초코'],
    correctIndex: 0,
    fact: '아이스 아메리카노 사랑꾼이에요 ☕',
  },
  {
    id: 'eunko-mint',
    characterId: 'eunko',
    question: '은코가 싫어하는 음식 조합은?',
    options: ['닭발·민트초코', '치즈·피클', '회·간장', '치킨·맥주'],
    correctIndex: 0,
    fact: '닭발도 민트초코도 둘 다 NO 🚫',
  },
  {
    id: 'eunko-cook',
    characterId: 'eunko',
    question: '은코가 잘 만드는 요리는?',
    options: ['파스타·짜파게티', '제육볶음', '김치찌개', '삼겹살'],
    correctIndex: 0,
    fact: '면 요리에 자신 있는 자취 요리 잘러 🍝',
  },
  {
    id: 'eunko-overwatch',
    characterId: 'eunko',
    question: '은코가 자주 하는 게임은?',
    options: ['오버워치·롤', '메이플스토리', '동물의 숲', '마인크래프트'],
    correctIndex: 0,
    fact: '오버워치와 롤이 메인, 실력파 게이머 🎮',
  },
  {
    id: 'eunko-english',
    characterId: 'eunko',
    question: '은코가 학교에서 가장 좋아했던 과목은?',
    options: ['영어', '수학', '체육', '음악'],
    correctIndex: 0,
    fact: '영어 능통, 일본어도 어느 정도 가능해요 🌏',
  },
  {
    id: 'eunko-realname',
    characterId: 'eunko',
    question: '은코의 본명은?',
    options: ['도은호', '남예준', '채봉구', '유하민'],
    correctIndex: 0,
    fact: '도은호, 별명 "douneo"의 유래 🐺',
  },
  {
    id: 'eunko-recruit',
    characterId: 'eunko',
    question: '은코가 PLCO에 합류시킨 멤버는?',
    options: ['밤코', '예코이', '아코', '하코이'],
    correctIndex: 0,
    fact: '밤코를 데려온 게 은코, 그래서 자주 티격태격해요 ⚡',
  },
  {
    id: 'eunko-hate',
    characterId: 'eunko',
    question: '은코가 가장 싫어하는 사람 유형은?',
    options: [
      '예의 없는 사람·위선자',
      '말 많은 사람',
      '낯가리는 사람',
      '시끄러운 사람',
    ],
    correctIndex: 0,
    fact: '예의 없거나 위선적인 사람을 가장 싫어해요 🙅',
  },
  {
    id: 'eunko-nickname',
    characterId: 'eunko',
    question: '아코가 은코에게 붙여준 별명은?',
    options: ['늑댕이 (늑대+댕댕이)', '범고래', '핑쬬', '햄냥이'],
    correctIndex: 0,
    fact: '늑대와 댕댕이 합친 "늑댕이"가 아코표 작명 🐺🐶',
  },
  {
    id: 'eunko-bloodtype',
    characterId: 'eunko',
    question: '은코의 혈액형은?',
    options: ['A형', 'B형', 'O형', 'AB형'],
    correctIndex: 0,
    fact: 'A형, 쌍둥이자리, 키 184cm 🐺',
  },
  {
    id: 'eunko-height',
    characterId: 'eunko',
    question: '은코의 키는?',
    options: ['184cm', '170cm', '178cm', '190cm'],
    correctIndex: 0,
    fact: '184cm, 멤버 중에서도 큰 편 📏',
  },
  {
    id: 'eunko-position',
    characterId: 'eunko',
    question: 'PLCO에서 은코의 메인 포지션은?',
    options: ['메인 래퍼 & 보컬', '메인 보컬', '메인 댄서', '리더'],
    correctIndex: 0,
    fact: '메인 래퍼이면서 보컬도 가능, 프로듀싱까지 🎙️',
  },
  {
    id: 'eunko-recruit-bamko',
    characterId: 'eunko',
    question: '은코가 PLCO에 영입한 멤버는?',
    options: ['밤코', '아코', '하코이', '예코이'],
    correctIndex: 0,
    fact: '밤코를 영입한 사람이 은코, 그 후로 자주 티격태격해요 ⚡',
  },
  {
    id: 'eunko-recruit-by',
    characterId: 'eunko',
    question: '은코를 PLCO에 합류시킨 사람은?',
    options: ['예코이', '아코', '밤코', '하코이'],
    correctIndex: 0,
    fact: '첫 트레이니였던 예코이가 아코와 함께 영입했어요 🤝',
  },
  {
    id: 'eunko-power',
    characterId: 'eunko',
    question: '은코의 특수 능력은?',
    options: ['손에서 불, 어두운 곳에서 빨간 눈', '물·거품', '바람', '얼음'],
    correctIndex: 0,
    fact: '손을 뒤집으면 불, 어두운 곳에서 눈이 빨갛게 빛나요 🔥',
  },
  {
    id: 'eunko-foodie',
    characterId: 'eunko',
    question: '은코의 음식 평가는?',
    options: ['단호하고 엄격함', '뭐든 잘 먹음', '편식', '안 가림'],
    correctIndex: 0,
    fact: '미식가, 맛 평가에 단호함, 별명도 "맛 인지자" 🍴',
  },
  {
    id: 'eunko-japan',
    characterId: 'eunko',
    question: '은코가 일본 무대에서 자신을 부를 때 쓰는 단어는?',
    options: ['おおかみ (늑대)', 'ワンちゃん (멍멍이)', 'ねこ (고양이)', 'ペット (펫)'],
    correctIndex: 0,
    fact: '일본 공식 SNS는 "ワンちゃん" 소개지만, 본인은 "늑대"라 해요 🐺',
  },
  {
    id: 'eunko-line-noah',
    characterId: 'eunko',
    question: '은코와 아코가 같이 들어간 라인은?',
    options: ['Producer Line, No-line', 'Dance Line', '리더 라인', 'Maknae Line'],
    correctIndex: 0,
    fact: '예준·아코·은코가 PLCO 곡 제작을 함께하는 프로듀서 라인 🎚️',
  },
  {
    id: 'eunko-pasta',
    characterId: 'eunko',
    question: '은코의 자취 요리 자신작은?',
    options: ['파스타·짜파게티', '제육볶음', '김치찌개', '닭갈비'],
    correctIndex: 0,
    fact: '면 요리만큼은 자신 있어요 🍝',
  },
  {
    id: 'eunko-perfume-brand',
    characterId: 'eunko',
    question: '은코가 사용하는 향수는?',
    options: ['Creed Aventus', 'CK One', 'Dior Sauvage', 'Tom Ford'],
    correctIndex: 0,
    fact: '크리드 아벤투스 매니아 🌟',
  },
  {
    id: 'eunko-horror',
    characterId: 'eunko',
    question: '공포 게임 중 은코의 반응은?',
    options: [
      '침착하게 "에임 좋았죠?"',
      '비명 지름',
      '게임 끔',
      '집중 못 함',
    ],
    correctIndex: 0,
    fact: '공포 게임에서도 멘탈 유지하며 잘해요 🎮',
  },
  {
    id: 'eunko-school',
    characterId: 'eunko',
    question: '은코의 자기 PR 멘트는?',
    options: [
      '바지락 칼국수 아스테룸 홍보대사',
      '대표 댄서',
      '메인 보컬',
      '비주얼 담당',
    ],
    correctIndex: 0,
    fact: '소개에 "바지락 칼국수 아스테룸 홍보대사"가 들어가요 🍜',
  },
  {
    id: 'eunko-eyes',
    characterId: 'eunko',
    question: '은코가 받은 자칭/타칭 별명이 아닌 것은?',
    options: [
      '돌고래 박사',
      '플러팅 황제',
      '천재 강아지',
      '가슴이 시끄러운 남자',
    ],
    correctIndex: 0,
    fact: '플러팅 황제·천재 강아지·가슴이 시끄러운 남자가 은코 소개 멘트 🐺',
  },
];
