import type { QuizQuestion } from '../../types';

// 하코 (하민) 🖤 검은 고양이
export const HAKO_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'hako-meal',
    characterId: 'hako',
    question: '하코이가 먹은 음식의 80%를 차지하는 것은?',
    options: ['라면', '빵', '김밥', '햄버거'],
    correctIndex: 0,
    fact: '뭘 먹었냐 물어보면 매번 라면이라고 답해요 🍜',
  },
  {
    id: 'hako-ramen',
    characterId: 'hako',
    question: '하코이가 가장 좋아하는 라면은?',
    options: ['스낵면', '신라면', '짜파게티', '진라면'],
    correctIndex: 0,
    fact: '라면 중에서도 스낵면을 최애로 꼽았어요 ✨',
  },
  {
    id: 'hako-mbti',
    characterId: 'hako',
    question: '하코이의 MBTI는?',
    options: ['INFJ-T', 'ENFP-T', 'ISTP-A', 'ENTP-T'],
    correctIndex: 0,
    fact: '낯가리는 INFJ, 막내인데 어른스러운 이유 🌙',
  },
  {
    id: 'hako-color',
    characterId: 'hako',
    question: '하코이의 시그니처 색은?',
    options: ['검정 🖤', '하양 🤍', '빨강 ❤️', '보라 💜'],
    correctIndex: 0,
    fact: '검은 고양이 + 블랙 하트가 하코이의 시그니처 🐈‍⬛',
  },
  {
    id: 'hako-animal',
    characterId: 'hako',
    question: '하코이의 대표 동물은?',
    options: ['검은 고양이', '흰 고양이', '햄스터', '강아지'],
    correctIndex: 0,
    fact: '검은 고양이가 하코이의 상징 🐈‍⬛',
  },
  {
    id: 'hako-nickname',
    characterId: 'hako',
    question: '하코이의 별명은?',
    options: ['햄냥이·비타민', '핑쬬', '늑댕이', '돌고래'],
    correctIndex: 0,
    fact: '햄냥이(hamnyangi)와 비타민(vithamin)이 대표 별명 🍊',
  },
  {
    id: 'hako-height',
    characterId: 'hako',
    question: '하코이의 키와 멤버 중 순위는?',
    options: [
      '185cm, 가장 큼',
      '170cm, 가장 작음',
      '178cm, 중간',
      '180cm, 두번째',
    ],
    correctIndex: 0,
    fact: '185cm로 PLCO 최장신, 게다가 막내 📏',
  },
  {
    id: 'hako-blood',
    characterId: 'hako',
    question: '하코이의 혈액형은?',
    options: ['AB형', 'A형', 'B형', 'O형'],
    correctIndex: 0,
    fact: '독특한 AB형 막내, 전갈자리 ♏',
  },
  {
    id: 'hako-taekwondo',
    characterId: 'hako',
    question: '하코이의 무술 실력은?',
    options: ['태권도 검은띠', '유도 갈색띠', '복싱 챔피언', '운동 못함'],
    correctIndex: 0,
    fact: '태권도 검은띠 보유자, 댄스에도 큰 도움이 돼요 🥋',
  },
  {
    id: 'hako-art',
    characterId: 'hako',
    question: '하코이의 의외의 예술 취미는?',
    options: ['그림 그리기 (아크릴화 카페 전시)', '뜨개질', '도자기', '서예'],
    correctIndex: 0,
    fact: '아크릴화를 그려서 Asterum 카페에 전시까지 했어요 🎨',
  },
  {
    id: 'hako-trot',
    characterId: 'hako',
    question: '하코이가 의외로 잘 부르는 장르는?',
    options: ['트로트', '오페라', '재즈', '메탈'],
    correctIndex: 0,
    fact: '트로트를 진심으로 좋아하고 잘 불러요 🎤',
  },
  {
    id: 'hako-impression',
    characterId: 'hako',
    question: '하코이의 숨겨진 특기는?',
    options: ['성대모사', '마술', '주짓수', '복화술'],
    correctIndex: 0,
    fact: '성대모사가 정확해서 자주 멤버들 따라해요 😼',
  },
  {
    id: 'hako-hate',
    characterId: 'hako',
    question: '하코이가 가장 싫어하는 것은?',
    options: ['거짓말·모기', '시끄러운 곳', '추위', '단 음식'],
    correctIndex: 0,
    fact: '거짓말과 모기를 진심으로 싫어해요 🦟',
  },
  {
    id: 'hako-partner',
    characterId: 'hako',
    question: '하코이와 함께 안무를 짜는 멤버는?',
    options: ['밤코', '예코이', '아코', '은코'],
    correctIndex: 0,
    fact: '댄스 라인 콤비, 안무 창작은 거의 둘이서 🕺',
  },
  {
    id: 'hako-language',
    characterId: 'hako',
    question: '하코이가 구사할 수 있는 외국어는?',
    options: ['일본어', '중국어', '스페인어', '독일어'],
    correctIndex: 0,
    fact: '일본어가 가능해서 일본 활동 때 빛나요 🇯🇵',
  },
  {
    id: 'hako-likes',
    characterId: 'hako',
    question: '하코이가 좋아한다고 자주 말하는 것은?',
    options: ['음식·운동·칭찬·게임', '잠·휴식·산책', '독서·영화·여행', '공부·일'],
    correctIndex: 0,
    fact: '특히 칭찬을 좋아해서 자주 칭찬 요청을 해요 🥰',
  },
  {
    id: 'hako-realname',
    characterId: 'hako',
    question: '하코이의 본명은?',
    options: ['유하민', '도은호', '한노아', '채봉구'],
    correctIndex: 0,
    fact: '본명 유하민, 본인은 "성 빼고 하민이라고 불러줘" 부탁 🐈‍⬛',
  },
  {
    id: 'hako-zodiac',
    characterId: 'hako',
    question: '하코이의 별자리는?',
    options: ['전갈자리', '쌍둥이자리', '처녀자리', '게자리'],
    correctIndex: 0,
    fact: '11월 1일생 전갈자리, AB형 🦂',
  },
  {
    id: 'hako-position',
    characterId: 'hako',
    question: 'PLCO에서 하코이의 메인 포지션은?',
    options: ['메인 댄서 & 리드 래퍼', '메인 보컬', '리더', '서브 보컬'],
    correctIndex: 0,
    fact: '댄스 라인 + 리드 래퍼, 막내인데 키도 가장 커요 💃',
  },
  {
    id: 'hako-debut-order',
    characterId: 'hako',
    question: '하코이는 PLCO의 몇 번째 멤버로 공개됐나?',
    options: ['다섯 번째 (막내, 마지막 공개)', '첫 번째', '세 번째', '네 번째'],
    correctIndex: 0,
    fact: '2023년 1월 16일 마지막 멤버로 공개된 막내 🐈‍⬛',
  },
  {
    id: 'hako-recruit-by',
    characterId: 'hako',
    question: '하코이를 PLCO에 데려온 멤버는?',
    options: ['아코', '예코이', '은코', '밤코'],
    correctIndex: 0,
    fact: '노아(아코)가 마지막 다섯 번째 멤버로 하코이를 데려왔어요 🤝',
  },
  {
    id: 'hako-line',
    characterId: 'hako',
    question: '하코이는 어느 라인 소속?',
    options: ['Ye-line (예준 라인)', 'No-line', 'Producer Line', 'Dance Line만'],
    correctIndex: 0,
    fact: '예준의 "Ye-line" 소속이자 댄스 라인 멤버 🌙',
  },
  {
    id: 'hako-chicken',
    characterId: 'hako',
    question: '하코이가 라면 다음으로 좋아하는 음식은?',
    options: ['치킨', '피자', '햄버거', '회'],
    correctIndex: 0,
    fact: '라면 80% + 치킨이 하코이의 음식 라인업 🍗',
  },
  {
    id: 'hako-ramen2',
    characterId: 'hako',
    question: '하코이가 스낵면 외에 좋아하는 라면은?',
    options: [
      '육개장 사발면·짜파게티',
      '신라면 블랙',
      '진라면 매운맛',
      '오뚜기 컵누들',
    ],
    correctIndex: 0,
    fact: '육개장 사발면도 짜파게티도 좋아해요 🍜',
  },
  {
    id: 'hako-catchphrase',
    characterId: 'hako',
    question: '하코이가 자주 하는 시그니처 말은?',
    options: ['논중화물', '예로롱', '바지락칼국수', '핑쬬'],
    correctIndex: 0,
    fact: '논쟁의 중심·화제의 물음표 = 논중화물 🔥',
  },
  {
    id: 'hako-belt',
    characterId: 'hako',
    question: '하코이의 태권도 단증은?',
    options: ['검은띠 (블랙벨트)', '갈색띠', '파란띠', '아무 단증 없음'],
    correctIndex: 0,
    fact: '진짜 검은띠 보유자, 댄스의 폭발력 비결 🥋',
  },
  {
    id: 'hako-bowling',
    characterId: 'hako',
    question: '하코이의 의외 취미가 아닌 것은?',
    options: ['스킨스쿠버', '볼링', '그림', '축구'],
    correctIndex: 0,
    fact: '볼링·그리기·영상 시청·축구가 공식 취미 🎳',
  },
  {
    id: 'hako-mosquito',
    characterId: 'hako',
    question: '하코이의 천적은?',
    options: ['모기', '벌', '나비', '거미'],
    correctIndex: 0,
    fact: '거짓말과 모기를 진심으로 싫어해요 🦟🚫',
  },
  {
    id: 'hako-jp',
    characterId: 'hako',
    question: '하코이가 일본 활동에서 빛나는 이유는?',
    options: ['일본어 가능', '일본 만화 매니아', '일식 전문가', '일본인 친구 많음'],
    correctIndex: 0,
    fact: '일본어 구사 가능, 일본 무대에서 자주 활약 🇯🇵',
  },
  {
    id: 'hako-blackbelt',
    characterId: 'hako',
    question: '하코이가 가장 자주 요청하는 것은?',
    options: ['칭찬', '간식', '휴식', '용돈'],
    correctIndex: 0,
    fact: '"칭찬받아야 더 잘해요"라는 말을 자주 해요 🥰',
  },
  {
    id: 'hako-acrylic',
    characterId: 'hako',
    question: '하코이의 그림이 전시된 곳은?',
    options: ['Asterum 433-10 카페', '서울 미술관', '학교 전시회', '본인 SNS만'],
    correctIndex: 0,
    fact: '아크릴화 한 점이 PLCO 공식 카페에 전시까지 됐어요 🎨',
  },
];
