import type { QuizQuestion } from '../../types';

// 예코 (예준) 💙 돌고래
export const YEKO_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'yeko-lamb',
    characterId: 'yeko',
    question: '예코이가 진심으로 좋아하는 고기는?',
    options: ['양고기', '삼겹살', '닭갈비', '소고기'],
    correctIndex: 0,
    fact: '오히려 향 나는 양고기를 더 선호할 정도로 진심입니다 🐑',
  },
  {
    id: 'yeko-redbean',
    characterId: 'yeko',
    question: '예코이가 좋아하는 단 음식은?',
    options: [
      '팥붕어빵·비비빅·양갱 (단팥)',
      '초콜릿',
      '캐러멜',
      '단 거 안 좋아함',
    ],
    correctIndex: 0,
    fact: '단팥 들어간 건 다 좋아할 정도로 단팥파입니다 🫘',
  },
  {
    id: 'yeko-game',
    characterId: 'yeko',
    question: '예코이가 게임 중에 유일하게 진심인 게임은?',
    options: [
      '크레이지 아케이드',
      '리그 오브 레전드',
      '배틀그라운드',
      '오버워치',
    ],
    correctIndex: 0,
    fact: '게임에 관심이 적은 편이지만 크아만큼은 진심입니다 💣',
  },
  {
    id: 'yeko-mbti',
    characterId: 'yeko',
    question: '예코이의 MBTI에서 J 비율은?',
    options: ['99% (극J)', '60% 정도', '50/50 경계', 'P 우세'],
    correctIndex: 0,
    fact: '재검사에서 J 99%가 나온 극J, 마감 한참 전부터 일정 세분화 📅',
  },
  {
    id: 'yeko-color',
    characterId: 'yeko',
    question: '예코이의 시그니처 색깔은?',
    options: ['파란색 💙', '보라색 💜', '분홍 💗', '빨강 ❤️'],
    correctIndex: 0,
    fact: '돌고래와 어울리는 파란색이 예코이의 시그니처 🐬',
  },
  {
    id: 'yeko-animal',
    characterId: 'yeko',
    question: '예코이를 대표하는 동물은?',
    options: ['돌고래', '범고래', '곰', '여우'],
    correctIndex: 0,
    fact: '대표 동물은 돌고래, 그래서 별명도 돌고래·범고래 🐬',
  },
  {
    id: 'yeko-drink',
    characterId: 'yeko',
    question: '예코이의 주량 순위는?',
    options: ['PLCO 1등', '중간 정도', '못 마심', '술 안 마심'],
    correctIndex: 0,
    fact: '"술은 짝으로 사야 한다"고 인정 받은 1등 🍺',
  },
  {
    id: 'yeko-soju',
    characterId: 'yeko',
    question: '예코이가 회식 때 고집하는 술은?',
    options: ['소주', '맥주', '와인', '하이볼'],
    correctIndex: 0,
    fact: '낮에는 맥주, 밤·회식에는 무조건 소주만 취급 🍶',
  },
  {
    id: 'yeko-noodle',
    characterId: 'yeko',
    question: '예코이가 좋아하는 라면은?',
    options: ['진라면 매운맛·틈새라면', '신라면', '안성탕면', '너구리'],
    correctIndex: 0,
    fact: '매운 음식 좋아하는 예코이답게 매콤한 라면 라인 🌶️',
  },
  {
    id: 'yeko-hate',
    characterId: 'yeko',
    question: '예코이가 가장 싫어하는 것은?',
    options: ['벌레·더운 날씨', '추위', '시끄러운 곳', '단 음식'],
    correctIndex: 0,
    fact: '여름과 벌레를 진심으로 싫어합니다 🪲☀️',
  },
  {
    id: 'yeko-shower',
    characterId: 'yeko',
    question: '예코이가 샤워할 때 특이한 습관은?',
    options: [
      '순서를 정해놓고 무조건 똑같이',
      '매일 다르게',
      '랜덤하게',
      '샤워 안 함',
    ],
    correctIndex: 0,
    fact: '레버 각도까지 똑같이 맞춰야 하루 루틴이 안 망가져요 🚿',
  },
  {
    id: 'yeko-hobby',
    characterId: 'yeko',
    question: '예코이의 취미가 아닌 것은?',
    options: ['축구', '기타 연주', '러닝', '커피'],
    correctIndex: 0,
    fact: '기타·러닝·커피·술이 예코이의 공식 취미 🎸',
  },
  {
    id: 'yeko-height',
    characterId: 'yeko',
    question: '예코이의 키는?',
    options: ['183cm', '170cm', '178cm', '190cm'],
    correctIndex: 0,
    fact: '183cm, B형, 처녀자리 ✨',
  },
  {
    id: 'yeko-perfume',
    characterId: 'yeko',
    question: '예코이가 좋아하는 향수 스타일은?',
    options: [
      '중성 향수 (BYREDO Blanche)',
      '달콤한 머스크',
      '시트러스',
      '향수 안 씀',
    ],
    correctIndex: 0,
    fact: '향수 매니아, 중성적인 Blanche가 시그니처 🌬️',
  },
  {
    id: 'yeko-tv',
    characterId: 'yeko',
    question: '예코이가 즐겨 보는 TV 장르는?',
    options: [
      '연애 프로그램 (나솔·환승연애·하트시그널)',
      '다큐멘터리',
      '뉴스',
      '스포츠 중계',
    ],
    correctIndex: 0,
    fact: '도파민이 터지는 연애 프로그램을 가리지 않습니다 💘',
  },
  {
    id: 'yeko-realname',
    characterId: 'yeko',
    question: '예코이의 본명은?',
    options: ['남예준', '도은호', '한노아', '채봉구'],
    correctIndex: 0,
    fact: '남예준, 그래서 "남리더"라는 별명도 생겼어요 👑',
  },
  {
    id: 'yeko-bloodtype',
    characterId: 'yeko',
    question: '예코이의 혈액형은?',
    options: ['B형', 'O형', 'A형', 'AB형'],
    correctIndex: 0,
    fact: '혈액형 B, 처녀자리, 가을 태생 ✨',
  },
  {
    id: 'yeko-dessert',
    characterId: 'yeko',
    question: '예코이가 좋아하는 디저트가 아닌 것은?',
    options: ['생크림 케이크', '스콘', '마카롱', '인절미'],
    correctIndex: 0,
    fact: '단팥·인절미·꿀떡·스콘·마카롱 같은 한식+서양 디저트를 좋아해요 🍰',
  },
  {
    id: 'yeko-snack',
    characterId: 'yeko',
    question: '예코이가 가장 좋아하는 간식은?',
    options: ['뭉친 김 (조미김)', '초콜릿', '과자', '아이스크림'],
    correctIndex: 0,
    fact: '간식이 김이라니, 예코이답죠 🌿',
  },
  {
    id: 'yeko-pineapple',
    characterId: 'yeko',
    question: '예코이가 싫어하는 음식은?',
    options: ['파인애플 피자', '닭발', '회', '청국장'],
    correctIndex: 0,
    fact: '의외로 파인애플 피자에 대해선 단호하게 NO 🍕🚫',
  },
  {
    id: 'yeko-skate',
    characterId: 'yeko',
    question: '예코이가 좋아하는 활동 중 하나는?',
    options: ['스케이트', '스키', '암벽등반', '서핑'],
    correctIndex: 0,
    fact: '스케이트 타는 걸 좋아해요 ⛸️',
  },
  {
    id: 'yeko-greeting',
    characterId: 'yeko',
    question: '예코이의 인사말은?',
    options: ['예로롱', '예이~', '예준이입니다', '뽀로롱'],
    correctIndex: 0,
    fact: '"예준 + 포롱"이 합쳐진 시그니처 인사 🐬',
  },
  {
    id: 'yeko-cafe-signoff',
    characterId: 'yeko',
    question: '예코이가 공식 카페 글 끝에 항상 쓰는 말은?',
    options: ['남예준 올림', '예준 드림', '예준이가', '안녕히 계세요'],
    correctIndex: 0,
    fact: '편지 형식으로 정중하게 "남예준 올림"으로 마무리 💌',
  },
  {
    id: 'yeko-bubble',
    characterId: 'yeko',
    question: '예코이의 특수 능력은?',
    options: ['물·거품을 다룸', '불을 다룸', '빛을 다룸', '바람을 다룸'],
    correctIndex: 0,
    fact: '물 줄기를 화면에 그리고 입에서 거품이 나오는 능력 💦',
  },
  {
    id: 'yeko-position',
    characterId: 'yeko',
    question: 'PLCO에서 예코이의 포지션은?',
    options: ['리더 & 메인 보컬', '메인 댄서', '메인 래퍼', '서브 보컬'],
    correctIndex: 0,
    fact: 'PLCO의 리더이자 메인 보컬, 작사·작곡까지 하는 만능 🎤',
  },
  {
    id: 'yeko-debut',
    characterId: 'yeko',
    question: 'PLCO 데뷔곡은?',
    options: ['기다릴게 (Wait For You)', 'Way 4 Luv', 'Pump Up The Volume', 'Virtual Idol'],
    correctIndex: 0,
    fact: '2023년 3월 12일 데뷔 앨범 ASTERUM 타이틀 곡 🌟',
  },
  {
    id: 'yeko-recruit',
    characterId: 'yeko',
    question: '예코이가 PLCO에 함께 데려온 멤버는?',
    options: ['노아·은호', '밤비·하민', '하민·밤비', '은호·하민'],
    correctIndex: 0,
    fact: '첫 트레이니였고, 노아와 은호를 그룹에 합류시켰어요 🤝',
  },
  {
    id: 'yeko-pork',
    characterId: 'yeko',
    question: '예코이가 국밥에 선호하는 고기는?',
    options: ['돼지고기 + 여러 가지', '소고기 한 가지', '닭고기', '국밥 안 먹음'],
    correctIndex: 0,
    fact: '돼지고기 베이스에 여러 고기를 섞어 먹는 걸 좋아해요 🍲',
  },
  {
    id: 'yeko-bug',
    characterId: 'yeko',
    question: '예코이가 진심으로 무서워하는 것은?',
    options: ['벌레', '귀신', '높은 곳', '바다'],
    correctIndex: 0,
    fact: '벌레라면 진심으로 도망갑니다 🪲🏃',
  },
];
