import type { Routine, RoutineItem } from '../types/routine';

const toItems = (exerciseIds: readonly string[]): RoutineItem[] =>
  exerciseIds.map((exerciseId, index) => ({ exerciseId, order: index + 1 }));

// 대중적으로 쓰이는 분할 루틴 시드. 사용자가 그대로 시작하거나 복제 후 커스텀한다.
// 종목 순서 = 우선순위(복합 → 고립). 세트/반복은 goal의 GOAL_SCHEME + 프로필 설정을 따른다.
export const PRESET_ROUTINES: readonly Routine[] = [
  {
    id: 'fullbody-a',
    name: '전신 루틴 A',
    split: 'fullBody',
    dayLabel: '전신 A',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['squat', 'bench-press', 'barbell-row', 'overhead-press', 'romanian-deadlift', 'plank']),
  },
  {
    id: 'fullbody-b',
    name: '전신 루틴 B',
    split: 'fullBody',
    dayLabel: '전신 B',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems([
      'leg-press',
      'incline-dumbbell-press',
      'lat-pulldown',
      'dumbbell-shoulder-press',
      'leg-curl',
      'hanging-leg-raise',
    ]),
  },
  {
    id: 'upper',
    name: '상체 루틴',
    split: 'upperLower',
    dayLabel: '상체',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['bench-press', 'barbell-row', 'overhead-press', 'lat-pulldown', 'barbell-curl', 'tricep-pushdown']),
  },
  {
    id: 'lower',
    name: '하체 루틴',
    split: 'upperLower',
    dayLabel: '하체',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['squat', 'romanian-deadlift', 'leg-press', 'leg-curl', 'calf-raise', 'hanging-leg-raise']),
  },
  {
    id: 'ppl-push',
    name: '푸시 데이',
    split: 'ppl',
    dayLabel: '푸시',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems([
      'bench-press',
      'incline-dumbbell-press',
      'overhead-press',
      'lateral-raise',
      'tricep-pushdown',
      'overhead-tricep-extension',
    ]),
  },
  {
    id: 'ppl-pull',
    name: '풀 데이',
    split: 'ppl',
    dayLabel: '풀',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['deadlift', 'pull-up', 'barbell-row', 'seated-cable-row', 'face-pull', 'barbell-curl']),
  },
  {
    id: 'ppl-legs',
    name: '레그 데이',
    split: 'ppl',
    dayLabel: '레그',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['squat', 'leg-press', 'romanian-deadlift', 'leg-curl', 'leg-extension', 'calf-raise']),
  },
  {
    id: 'bro-chest',
    name: '가슴 데이',
    split: 'broSplit',
    dayLabel: '가슴',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['bench-press', 'incline-bench-press', 'dumbbell-bench-press', 'cable-fly', 'dips']),
  },
  {
    id: 'bro-back',
    name: '등 데이',
    split: 'broSplit',
    dayLabel: '등',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['deadlift', 'pull-up', 'barbell-row', 'seated-cable-row', 't-bar-row']),
  },
  {
    id: 'bro-shoulders',
    name: '어깨 데이',
    split: 'broSplit',
    dayLabel: '어깨',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['overhead-press', 'dumbbell-shoulder-press', 'lateral-raise', 'cable-lateral-raise', 'face-pull']),
  },
  {
    id: 'bro-legs',
    name: '하체 데이',
    split: 'broSplit',
    dayLabel: '하체',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems(['squat', 'leg-press', 'romanian-deadlift', 'leg-curl', 'leg-extension', 'calf-raise']),
  },
  {
    id: 'bro-arms',
    name: '팔 데이',
    split: 'broSplit',
    dayLabel: '팔',
    goal: 'hypertrophy',
    source: 'preset',
    items: toItems([
      'barbell-curl',
      'dumbbell-curl',
      'hammer-curl',
      'tricep-pushdown',
      'overhead-tricep-extension',
      'close-grip-bench-press',
    ]),
  },
];
