import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { colors } from '../src/colors';
import { shadow } from '../src/shadow';
import { container, radius, spacing } from '../src/spacing';
import { fontFamily, fontSize, fontWeight } from '../src/typography';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = resolve(__dirname, '../generated/theme.css');

const indent = (lines: string[]) => lines.map((l) => `  ${l}`).join('\n');

/** light 값으로 :root, dark 값으로 .dark 블록을 만든다. */
function buildColorVars() {
  const rootLines: string[] = [];
  const darkLines: string[] = [];
  for (const [name, value] of Object.entries(colors)) {
    rootLines.push(`--color-${name}: ${value.light};`);
    darkLines.push(`--color-${name}: ${value.dark};`);
  }
  return { rootLines, darkLines };
}

/** 테마 무관 토큰(폰트/크기/굵기/여백/반경)을 :root 변수로 만든다. */
function buildStaticVars() {
  const lines: string[] = [];
  for (const [name, value] of Object.entries(fontFamily)) {
    lines.push(`--font-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(fontSize)) {
    lines.push(`--text-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(fontWeight)) {
    lines.push(`--font-weight-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(spacing)) {
    lines.push(`--spacing-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(radius)) {
    lines.push(`--radius-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(shadow)) {
    lines.push(`--shadow-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(container)) {
    lines.push(`--container-${name}: ${value};`);
  }
  return lines;
}

/** Tailwind가 유틸리티를 생성하도록 토큰 이름을 @theme inline에 매핑한다. */
function buildThemeMap() {
  const lines: string[] = [];
  for (const name of Object.keys(colors)) {
    lines.push(`--color-${name}: var(--color-${name});`);
  }
  for (const name of Object.keys(fontFamily)) {
    lines.push(`--font-${name}: var(--font-${name});`);
  }
  for (const name of Object.keys(fontSize)) {
    lines.push(`--text-${name}: var(--text-${name});`);
  }
  for (const name of Object.keys(fontWeight)) {
    lines.push(`--font-weight-${name}: var(--font-weight-${name});`);
  }
  for (const name of Object.keys(spacing)) {
    lines.push(`--spacing-${name}: var(--spacing-${name});`);
  }
  for (const name of Object.keys(radius)) {
    lines.push(`--radius-${name}: var(--radius-${name});`);
  }
  for (const name of Object.keys(shadow)) {
    lines.push(`--shadow-${name}: var(--shadow-${name});`);
  }
  for (const name of Object.keys(container)) {
    lines.push(`--container-${name}: var(--container-${name});`);
  }
  return lines;
}

function generate() {
  const { rootLines, darkLines } = buildColorVars();
  const staticLines = buildStaticVars();
  const themeLines = buildThemeMap();

  const css = `/**
 * AUTO-GENERATED by @tokens/css — 직접 수정하지 마세요.
 * 토큰 변경은 packages/tokens/src/*.ts 에서 한 뒤 \`pnpm tokens\`를 실행하세요.
 */

@custom-variant dark (&:where(.dark, .dark *));

:root {
${indent([...rootLines, '', ...staticLines])}
}

.dark {
${indent(darkLines)}
}

@theme inline {
${indent(themeLines)}
}
`;

  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, css, 'utf8');
  console.log(`✓ design tokens → ${OUT_FILE}`);
}

generate();
