import type { Exercise } from '../types/exercise';

// 종목 마스터 데이터(시드). 부위·기구·대체관계를 담아 추천과 대체운동 제안의 토대가 된다.
// 사용자가 직접 입력한 루틴이 쌓이면 빈도 기반 추천이 이 시드를 보강한다(PRD 5장).
export const EXERCISES = [
  // 가슴
  {
    id: 'bench-press',
    nameKo: '바벨 벤치프레스',
    nameEn: 'Barbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['dumbbell-bench-press', 'machine-chest-press', 'push-up'],
  },
  {
    id: 'incline-bench-press',
    nameKo: '인클라인 벤치프레스',
    nameEn: 'Incline Barbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['incline-dumbbell-press', 'incline-machine-press', 'machine-chest-press'],
  },
  {
    id: 'dumbbell-bench-press',
    nameKo: '덤벨 벤치프레스',
    nameEn: 'Dumbbell Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'dumbbell',
    movementType: 'compound',
    alternativeIds: ['bench-press', 'machine-chest-press'],
  },
  {
    id: 'incline-dumbbell-press',
    nameKo: '인클라인 덤벨 프레스',
    nameEn: 'Incline Dumbbell Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    movementType: 'compound',
    alternativeIds: ['incline-bench-press', 'incline-machine-press', 'machine-chest-press'],
  },
  {
    id: 'machine-chest-press',
    nameKo: '체스트 프레스 머신',
    nameEn: 'Machine Chest Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    movementType: 'compound',
    alternativeIds: ['bench-press', 'dumbbell-bench-press', 'incline-machine-press'],
  },
  {
    id: 'incline-machine-press',
    nameKo: '인클라인 체스트 프레스 머신',
    nameEn: 'Incline Machine Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'machine',
    movementType: 'compound',
    alternativeIds: ['incline-bench-press', 'incline-dumbbell-press', 'machine-chest-press'],
  },
  {
    id: 'decline-bench-press',
    nameKo: '디클라인 벤치프레스',
    nameEn: 'Decline Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['bench-press', 'machine-chest-press', 'dips'],
  },
  {
    id: 'smith-bench-press',
    nameKo: '스미스 벤치프레스',
    nameEn: 'Smith Machine Bench Press',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'smith',
    movementType: 'compound',
    alternativeIds: ['bench-press', 'machine-chest-press'],
  },
  {
    id: 'cable-fly',
    nameKo: '케이블 플라이',
    nameEn: 'Cable Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: 'cable',
    movementType: 'isolation',
    alternativeIds: ['pec-deck-fly', 'dumbbell-fly'],
  },
  {
    id: 'pec-deck-fly',
    nameKo: '펙덱 플라이',
    nameEn: 'Pec Deck Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: 'machine',
    movementType: 'isolation',
    alternativeIds: ['cable-fly', 'dumbbell-fly'],
  },
  {
    id: 'dumbbell-fly',
    nameKo: '덤벨 플라이',
    nameEn: 'Dumbbell Fly',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementType: 'isolation',
    alternativeIds: ['cable-fly', 'pec-deck-fly'],
  },
  {
    id: 'push-up',
    nameKo: '푸시업',
    nameEn: 'Push-up',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: 'bodyweight',
    movementType: 'compound',
    alternativeIds: ['bench-press', 'machine-chest-press'],
  },
  {
    id: 'dips',
    nameKo: '딥스',
    nameEn: 'Dips',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps'],
    equipment: 'bodyweight',
    movementType: 'compound',
    alternativeIds: ['machine-chest-press', 'close-grip-bench-press'],
  },

  // 등
  {
    id: 'deadlift',
    nameKo: '데드리프트',
    nameEn: 'Deadlift',
    primaryMuscle: 'back',
    secondaryMuscles: ['hamstrings', 'glutes'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['romanian-deadlift', 'barbell-row'],
  },
  {
    id: 'pull-up',
    nameKo: '풀업',
    nameEn: 'Pull-up',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'bodyweight',
    movementType: 'compound',
    alternativeIds: ['lat-pulldown', 'machine-row'],
  },
  {
    id: 'lat-pulldown',
    nameKo: '랫풀다운',
    nameEn: 'Lat Pulldown',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    movementType: 'compound',
    alternativeIds: ['pull-up', 'machine-row'],
  },
  {
    id: 'barbell-row',
    nameKo: '바벨 로우',
    nameEn: 'Barbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['dumbbell-row', 'seated-cable-row', 'machine-row'],
  },
  {
    id: 'dumbbell-row',
    nameKo: '덤벨 로우',
    nameEn: 'Dumbbell Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    movementType: 'compound',
    alternativeIds: ['barbell-row', 'seated-cable-row'],
  },
  {
    id: 'seated-cable-row',
    nameKo: '시티드 케이블 로우',
    nameEn: 'Seated Cable Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    movementType: 'compound',
    alternativeIds: ['machine-row', 'barbell-row'],
  },
  {
    id: 'machine-row',
    nameKo: '머신 로우',
    nameEn: 'Machine Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'machine',
    movementType: 'compound',
    alternativeIds: ['seated-cable-row', 'dumbbell-row'],
  },
  {
    id: 't-bar-row',
    nameKo: '티바 로우',
    nameEn: 'T-Bar Row',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['barbell-row', 'machine-row'],
  },

  // 어깨
  {
    id: 'overhead-press',
    nameKo: '오버헤드 프레스',
    nameEn: 'Overhead Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['dumbbell-shoulder-press', 'machine-shoulder-press'],
  },
  {
    id: 'dumbbell-shoulder-press',
    nameKo: '덤벨 숄더 프레스',
    nameEn: 'Dumbbell Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    movementType: 'compound',
    alternativeIds: ['overhead-press', 'machine-shoulder-press'],
  },
  {
    id: 'machine-shoulder-press',
    nameKo: '머신 숄더 프레스',
    nameEn: 'Machine Shoulder Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'machine',
    movementType: 'compound',
    alternativeIds: ['overhead-press', 'dumbbell-shoulder-press'],
  },
  {
    id: 'arnold-press',
    nameKo: '아놀드 프레스',
    nameEn: 'Arnold Press',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: 'dumbbell',
    movementType: 'compound',
    alternativeIds: ['dumbbell-shoulder-press', 'overhead-press'],
  },
  {
    id: 'lateral-raise',
    nameKo: '사이드 래터럴 레이즈',
    nameEn: 'Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementType: 'isolation',
    alternativeIds: ['cable-lateral-raise', 'machine-lateral-raise'],
  },
  {
    id: 'cable-lateral-raise',
    nameKo: '케이블 래터럴 레이즈',
    nameEn: 'Cable Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'cable',
    movementType: 'isolation',
    alternativeIds: ['lateral-raise', 'machine-lateral-raise'],
  },
  {
    id: 'machine-lateral-raise',
    nameKo: '머신 래터럴 레이즈',
    nameEn: 'Machine Lateral Raise',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'machine',
    movementType: 'isolation',
    alternativeIds: ['lateral-raise', 'cable-lateral-raise'],
  },
  {
    id: 'face-pull',
    nameKo: '페이스 풀',
    nameEn: 'Face Pull',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'cable',
    movementType: 'isolation',
    alternativeIds: ['reverse-pec-deck'],
  },
  {
    id: 'reverse-pec-deck',
    nameKo: '리버스 펙덱',
    nameEn: 'Reverse Pec Deck',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'machine',
    movementType: 'isolation',
    alternativeIds: ['face-pull'],
  },

  // 하체 (대퇴사두)
  {
    id: 'squat',
    nameKo: '바벨 스쿼트',
    nameEn: 'Barbell Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['leg-press', 'hack-squat', 'goblet-squat'],
  },
  {
    id: 'front-squat',
    nameKo: '프론트 스쿼트',
    nameEn: 'Front Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['squat', 'leg-press'],
  },
  {
    id: 'leg-press',
    nameKo: '레그 프레스',
    nameEn: 'Leg Press',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    movementType: 'compound',
    alternativeIds: ['squat', 'hack-squat'],
  },
  {
    id: 'hack-squat',
    nameKo: '핵 스쿼트',
    nameEn: 'Hack Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    movementType: 'compound',
    alternativeIds: ['leg-press', 'squat'],
  },
  {
    id: 'goblet-squat',
    nameKo: '고블릿 스쿼트',
    nameEn: 'Goblet Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    movementType: 'compound',
    alternativeIds: ['squat', 'leg-press'],
  },
  {
    id: 'leg-extension',
    nameKo: '레그 익스텐션',
    nameEn: 'Leg Extension',
    primaryMuscle: 'quads',
    secondaryMuscles: [],
    equipment: 'machine',
    movementType: 'isolation',
    alternativeIds: ['hack-squat'],
  },
  {
    id: 'lunge',
    nameKo: '런지',
    nameEn: 'Lunge',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    movementType: 'compound',
    alternativeIds: ['bulgarian-split-squat', 'leg-press'],
  },
  {
    id: 'bulgarian-split-squat',
    nameKo: '불가리안 스플릿 스쿼트',
    nameEn: 'Bulgarian Split Squat',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    movementType: 'compound',
    alternativeIds: ['lunge'],
  },

  // 하체 (햄스트링/둔근)
  {
    id: 'romanian-deadlift',
    nameKo: '루마니안 데드리프트',
    nameEn: 'Romanian Deadlift',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['leg-curl', 'deadlift'],
  },
  {
    id: 'leg-curl',
    nameKo: '레그 컬',
    nameEn: 'Leg Curl',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: [],
    equipment: 'machine',
    movementType: 'isolation',
    alternativeIds: ['romanian-deadlift'],
  },
  {
    id: 'hip-thrust',
    nameKo: '힙 쓰러스트',
    nameEn: 'Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['glute-bridge', 'leg-press'],
  },
  {
    id: 'glute-bridge',
    nameKo: '글루트 브릿지',
    nameEn: 'Glute Bridge',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'bodyweight',
    movementType: 'compound',
    alternativeIds: ['hip-thrust'],
  },
  {
    id: 'calf-raise',
    nameKo: '카프 레이즈',
    nameEn: 'Calf Raise',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    movementType: 'isolation',
    alternativeIds: [],
  },

  // 이두
  {
    id: 'barbell-curl',
    nameKo: '바벨 컬',
    nameEn: 'Barbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    movementType: 'isolation',
    alternativeIds: ['dumbbell-curl', 'cable-curl'],
  },
  {
    id: 'dumbbell-curl',
    nameKo: '덤벨 컬',
    nameEn: 'Dumbbell Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementType: 'isolation',
    alternativeIds: ['barbell-curl', 'cable-curl'],
  },
  {
    id: 'hammer-curl',
    nameKo: '해머 컬',
    nameEn: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementType: 'isolation',
    alternativeIds: ['dumbbell-curl'],
  },
  {
    id: 'cable-curl',
    nameKo: '케이블 컬',
    nameEn: 'Cable Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'cable',
    movementType: 'isolation',
    alternativeIds: ['dumbbell-curl', 'barbell-curl'],
  },

  // 삼두
  {
    id: 'tricep-pushdown',
    nameKo: '트라이셉 푸시다운',
    nameEn: 'Tricep Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    movementType: 'isolation',
    alternativeIds: ['overhead-tricep-extension', 'close-grip-bench-press'],
  },
  {
    id: 'overhead-tricep-extension',
    nameKo: '오버헤드 트라이셉 익스텐션',
    nameEn: 'Overhead Tricep Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    movementType: 'isolation',
    alternativeIds: ['tricep-pushdown'],
  },
  {
    id: 'close-grip-bench-press',
    nameKo: '클로즈그립 벤치프레스',
    nameEn: 'Close-grip Bench Press',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest'],
    equipment: 'barbell',
    movementType: 'compound',
    alternativeIds: ['dips', 'tricep-pushdown'],
  },

  // 코어
  {
    id: 'plank',
    nameKo: '플랭크',
    nameEn: 'Plank',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    movementType: 'isolation',
    alternativeIds: ['ab-rollout'],
  },
  {
    id: 'hanging-leg-raise',
    nameKo: '행잉 레그 레이즈',
    nameEn: 'Hanging Leg Raise',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    movementType: 'isolation',
    alternativeIds: ['cable-crunch'],
  },
  {
    id: 'cable-crunch',
    nameKo: '케이블 크런치',
    nameEn: 'Cable Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'cable',
    movementType: 'isolation',
    alternativeIds: ['hanging-leg-raise'],
  },
  {
    id: 'ab-rollout',
    nameKo: '앱 롤아웃',
    nameEn: 'Ab Rollout',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    movementType: 'isolation',
    alternativeIds: ['plank'],
  },
] as const satisfies readonly Exercise[];

export type ExerciseId = (typeof EXERCISES)[number]['id'];

const exerciseById: Partial<Record<ExerciseId, Exercise>> = {};
for (const exercise of EXERCISES) {
  exerciseById[exercise.id] = exercise;
}

export const EXERCISE_BY_ID = exerciseById as Record<ExerciseId, Exercise>;

// 런타임 문자열(세션·루틴의 exerciseId)로 안전 조회. 없는 id면 undefined.
export const getExerciseById = (id: string): Exercise | undefined => EXERCISE_BY_ID[id as ExerciseId];
